//arabic translate
//need key of String and String value to show
Map<String, String> arabicLanguage = {
  //forget password
  "Password Reset Mail has been sent to your authorized Email":
      "تم إرسال بريد إعادة تعيين كلمة المرور إلى البريد الإلكتروني المعتمد الخاص بك",
  'Forget Password': 'نسيت كلمة المرور',
  "Please enter your email": "رجاء أدخل بريدك الإلكتروني",
  "We will send you a verify code to your\nemail":
      "سوف نرسل لك رمز التحقق إلى البريد الإلكتروني\n الخاص بك",
  "(Required)": "(مطلوب)",
  //login
  "Login successfully": "تم تسجيل الدخول بنجاح",
  'Login': 'تسجيل الدخول',
  "Welcome Back": "مرحبًا بعودتك",
  "Please Log in To Continue": "الرجاء تسجيل الدخول للمتابعة",
  "Don't have an account ?": "ليس لديك حساب ؟",
  "Register now": "أنشئ حساب الأن",
  "This account has been deleted. Contact the administration to restore it":
      "تم حذف هذا الحساب قم بالتواصل مع الإدارة لاستعادته",
  //register
  'Select Company':'اختر شركة',
  'Select Service':'اختر خدمة',
  "Account created successfully please login ":
      "تم إنشاء الحساب بنجاح يرجى تسجيل الدخول",
  'Register': 'إنشاء حساب',
  "Create account": 'إنشاء حساب',
  "New to our platform? Complete the details below.":
      "هل أنت جديد في منصتنا؟ أكمل التفاصيل أدناه.",
  "You have an account ?": "لديك حساب ؟",
  '(Optional)': '(اختياري)',
  " English Responsible Person Name :": "اسم الشخص المسؤول باللغة الإنجليزية :",
  " Arabic Responsible Person Name :": "اسم الشخص المسؤول باللغة العربية :",
  " Responsible Person Mobile :": "رقم هاتف الشخص المسؤول :",
  " Princedom Name :": "إسم الإمارة :",
  'Person': 'سائق',
  'Company': 'شركة',
  'Upload Image (Optional)': 'ارفع الصورة (اختياري)',
  "Replace Image": "استبدال الصورة",
  "Delete Image": "حذف الصورة",
  "View Full Image": "عرض الصورة كاملة",
  " English Company Name :": "اسم الشركة بالانجليزية :",
  " Arabic Company Name :": "اسم الشركة بالعربية :",
  //helper
  "Failed to lunch": "فشل في التشغيل",
  'Please enter a valid name': 'رجاء ادخل اسما صحيحا',
  'Please enter a valid email': 'يرجى إدخال بريد إلكتروني صحيح',
  'Please enter a valid phone number': 'يرجى إدخال رقم هاتف صالح',
  "This field is required": "هذه الحقل مطلوبه",
  "Can't be less than": "لا يمكن أن يكون أقل من",
  "Can't be more than": "لا يمكن أن يكون أكثر من",
  "Doesn't compare": "لا يوجد تطابق",

  //Dio errors
  "No internet connection": "لا يوجد اتصال بالانترنت",
  "TimeOut for the request": "انتهت مهلة الطلب",
  'Something went wrong': 'حدث شيئ ما خاطئ',
  'Retry': 'أعد المحاولة',
  //profile
  'Profile': 'الملف الشخصي',
  'Edit Profile': 'تعديل الملف الشخصي',
  'Orders': 'الطلبات',
  'Points': 'النقاط',
  'Delete Account': 'حذف الحساب',
  'Log Out': 'تسجيل الخروج',
  "Logout successfully": "تم تسجيل الخروج بنجاح",
  "Account Deleted successfully": "تم حذف الحساب بنجاح",
  "Yes": "نعم",
  "No": "لا",
  "Are you sure you want to delete this account ?":
      " هل أنت متأكد أنك تريد حذف الحساب ؟ ",
  'Contact us': 'اتصل بنا',
  'Privacy policy': 'سياسة الخصوصية',
  'About us': 'حولنا',
  'Terms & Conditions': 'الشروط والاحكام',
  //edit profile
  "Updated successfully": "تم التحديث بنجاح",
  "Save": "حفظ",
  'Company en name': 'اسم الشركة بالعربية',
  'Company ar name': 'اسم الشركة بالانجليرية',
  'Email': 'البريد الالكتروني',
  'Phone': 'رقم الهاتف',
  'Arabic person name': 'اسم الشخص المسؤول بالعربية',
  'English person name': 'اسم الشخص المسؤؤل بالانجليزية',
  'Person Phone': 'رقم الشخص المسؤول',
  'Select nation': 'اختر دولة',
  'Princedom': 'الإمارة',
  'Address': 'العنوان',
  " Name :": " الاسم :",
  " Phone Number :": " رقم الهاتف :",
  " Email :": " البريد الالكتوني :",
  " Address :": " العنوان :",
  " Princedom :": " الإمارة :",
  //contact us
  "Message send successfully": "تم إرسال الرسالة بنجاح",
  "Write your message": "اكتب رسالتك",
  'write your message her': 'اكتب رسالتك هنا',
  'Send': 'إرسال',
  'Title': "العنوان",
  'Contact Us':'اتصل بنا',
  //choose location
  "Warning": "تحزير",
  "Please enable location Service": "الرجاء تفعيل خدمات الموقع",
  "Please give permission for location to use this app":
      "الرجاء إعطاء سماحيات الوصول الى الموقع لهذا التطبيق",
  "You can't use this app with out location service please enable location permission for this app from your device settings":
      "لا يمكنك استخدام هذا التطبيق بدون خدمة الموقع، يرجى تمكين إذن الموقع لهذا التطبيق من إعدادات جهازك",
  'Choose Location': 'اختر الموقع',
  "You can't use this app with out location permission":
      "لا يمكنك استخدام هذا التطبيق بدون إذن تحديد الموقع",
  "Please enable location permission for this app from your device settings":
      "يرجى تمكين إذن الموقع لهذا التطبيق من إعدادات جهازك",
  "Continue": "استمر",
  //services order details
  "Services Order Details": "تفاصيل طلب الخدمة",
  "Service Provider :": "مقدم الخدمة : ",
  'Service Name : ': 'اسم الخدمة : ',
    "Client Details :": "تفاصيل الزيون : ",
  'Client Email : ': 'البريد الإلكتروني للزيون : ',
  'Client Phone Number : ': 'رقم الهاتف للزيون : ',
  'Company Responsible Person Mobile : ': 'رقم الشخص المسؤول عن الشركة : ',
  'Company Email : ': 'البريد الإلكتروني للشركة : ',
  "Driver Details :": "تفاصيل السائق : ",
  'Email : ': 'البريد الإلكتروني : ',
  'Address : ': 'العنوان : ',
  'Phone : ': 'رقم الهاتف : ',
  "Order Details :": "تفاصيل الطلب  : ",
  'Service Cost : ': 'تكلفة الخدمة : ',
  'Service Cost After Offer : ': 'تكلفة الخدمة بعد الحسم : ',
  'Payment Way : ': 'وسيلة الدفع : ',
  "Accepted": "موافق عليه",

  //company orders
  'Newest': 'الأحدث',
  'Oldest': "الأقدم",
  'Product': 'منتجات',
  'Order by': 'ترتيب حسب',
  'Type': 'النوع',
  'Service': 'خدمات',
  'Search...': 'بحث...',
  "Pending": "قيد الانتظار",
  "Done": "منتهي",
  "Rejected": "مرفوض",
  "Order : ":"طلب : ",
  "order rejected":"تم رفض الطلب",
  "order accepted":"تم قبول الطلب",
  "Operation failed try again":"فشلت العملية اعد المحاولة",
  //driver orders
  "Client Name : ":"اسم الزبون : ",
  "Company Name : ": "اسم الشركة : ",
  "Driver Name : ": "اسم السائق : ",
  "Payment way : ": "طريقة الدفع : ",
  "Total : ": "المجموع : ",
  'AED': 'د.إ',
  "Status : ": "الحالة : ",
  "Reject": "رفض",
  "Accept": "قبول",

  // Order Tracking
  "Order Tracking": "تتبع الطلب",
  'Complete Order': 'اكمل الطلب',
  'Alert': 'تنبيه',
  "Are you sure you want to complete this order ?":
      "هل أنت متاكد من انك تريد الانتهاء من هذا الطلب؟",
  "Tap to call": "اضغط هنا للاتصال",

  //order details
  "Order details": "تفاصيل الطلب",
  'Quantity :': 'الكمية :',
  'Order number ': 'رقم الطلب',
  'Total Price ': ' السعر الكلي',
  'Price After Discount ': 'السعر بعد الخصم',
  'Currency ': 'العملة',
  'Date ': 'التاريخ',
  'Coupon code ': 'كود الكوبون',
  'Payment method ': 'طريقة الدفع',
  "cash":"نقدي",
   "pending":"بانتظار القبول",
};
